name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Ruby の脆弱性スキャン
  scan_ruby:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
      - run: gem install bundler
      - run: bundle install --jobs 4 --retry 3
      - run: bundle exec brakeman --no-exit-on-warn

  # RuboCop 静的解析
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
      - run: gem install rubocop
      - run: bundle exec rubocop

  # Rails テスト実行
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      # 必要なら JS 依存があればここでセットアップ
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: '16'
      # - run: npm ci

      - run: gem install bundler
      - run: bundle install --jobs 4 --retry 3

      # CI 用 DB 設定をコピー
      - run: cp config/database.yml.ci config/database.yml

      # DB 作成＆スキーマロード
      - run: |
          bundle exec rails db:create
          bundle exec rails db:schema:load

      # テスト実行
      - run: bundle exec rails test
