name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Ruby の脆弱性スキャン
  scan_ruby:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true        # ← Bundler キャッシュ

      - name: Add Linux platform to lockfile
        run: bundle lock --add-platform x86_64-linux

      - name: Install Gems
        run: bundle install --jobs 4 --retry 3

      - name: Run Brakeman
        run: bundle exec brakeman --no-exit-on-warn

  # RuboCop 静的解析
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true

      - name: Add Linux platform to lockfile
        run: bundle lock --add-platform x86_64-linux

      - name: Install Gems
        run: bundle install --jobs 4 --retry 3

      - name: Run RuboCop
        run: bundle exec rubocop

  # Rails テスト実行
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true

      - name: Add Linux platform to lockfile
        run: bundle lock --add-platform x86_64-linux

      - name: Install system dependencies for PostgreSQL
        run: sudo apt-get update && sudo apt-get install -y libpq-dev

      - name: Install Gems
        run: bundle install --jobs 4 --retry 3

      - name: Prepare database.yml
        run: cp config/database.yml.ci config/database.yml

      - name: Create test database & load schema
        run: |
          RAILS_ENV=test bundle exec rails db:create db:schema:load

      - name: Run test suite
        run: bundle exec rails test
